project:
  type: website

website:
  page-navigation: true
  title: "IAFF 6501--Spring 2024 Schedule"
  description: "Homepage for IAFF 6501, George Washington University."
  site-url: "https://dataviz-gwu.rocks"
  repo-url: "https://github.com/eteitelbaum/dataviz-summer-2023"
  repo-actions: [edit, issue]
  open-graph: true
  favicon: "images/iaff6501-logo.png"
  twitter-card: true
  reader-mode: true
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/). üë∑üõ†Ô∏è"
    left: "&copy; Copyright 2024, [Emmanuel Teitelbaum](https://emmanuel.teitelbaum.com)"
    background: "#1F45FC"
  sidebar:
    background: "#1F45FC"
    logo: "images/iaff6501-logo.png"
    pinned: true
    align: center
    tools:
      - icon: mortarboard-fill
        text: "Blackboard"
        href: https://blackboard.gwu.edu
      - icon: github
        href: https://classroom.github.com
        text: "Github Classroom"
      - icon: r-project # bootstrap-reboot
        href: https://posit.co/download/rstudio-desktop
        text: "RStudio Desktop"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: instructor.qmd
            text: Instructor
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          # - href: faq.qmd
          #   text: FAQ
      - section: "Weekly Materials"
        contents: 
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
          - href: weeks/week-7.qmd
            text: "Week 7"
          - href: weeks/week-8.qmd
            text: "Week 8"
          - href: weeks/week-9.qmd
            text: "Week 9"
          - href: weeks/week-10.qmd
            text: "Week 10"
          - href: weeks/week-11.qmd
            text: "Week 11"
          - href: weeks/week-12.qmd
            text: "Week 12"
          - href: weeks/week-13.qmd
            text: "Week 13"
          - href: weeks/week-14.qmd
            text: "Week 14"
      - section: "Homework"
        contents:
          - href: assignments/homework-1.qmd
            text: "Homework 1"
          - href: assignments/homework-2.qmd
            text: "Homework 2"
          - href: assignments/homework-3.qmd
            text: "Homework 3"
      - section: "Final Project"
        contents:
          - href: project/project-description.qmd
            text: "Final Project"
          - href: project/project-datasets.qmd
            text: "Datasets"
      - section: "Course Modules"
        contents:
          - href: modules/module-1.1.qmd
            text: "Module 1.1"
          - href: modules/module-1.2.qmd
            text: "Module 1.2"
          - href: modules/module-2.1.qmd
            text: "Module 2.1"
          - href: modules/module-2.2.qmd
            text: "Module 2.2"
          - href: modules/module-3.1.qmd
            text: "Module 3.1"
          - href: modules/module-3.2.qmd
            text: "Module 3.2"
          - href: modules/module-4.1.qmd
            text: "Module 4.1"
          - href: assignments/homework-1.qmd
            text: "Module 4.2"
          - href: modules/module-5.1.qmd
            text: "Module 5.1"
          - href: modules/module-5.2.qmd
            text: "Module 5.2"
          - href: modules/module-6.1.qmd
            text: "Module 6.1"
          - href: modules/module-6.2.qmd
            text: "Module 6.2"
          - href: modules/module-7.1.qmd
            text: "Module 7.1"
          - href: modules/module-7.2.qmd
            text: "Module 7.2"
          - href: modules/module-9.1.qmd
            text: "Module 9.1"
          - href: modules/module-9.2.qmd
            text: "Module 9.2"
          - href: modules/module-10.1.qmd
            text: "Module 10.1"
          - href: modules/module-10.2.qmd
            text: "Module 10.2"
          - href: modules/module-10.3.qmd
            text: "Module 10.3 (Optional)"
          - href: modules/module-11.1.qmd
            text: "Module 11.1"
          - href: modules/module-11.2.qmd
            text: "Module 11.2"
          - href: modules/module-12.1.qmd
            text: "Module 12.1"
          - href: modules/module-12.2.qmd
            text: "Module 12.2"
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true
freeze: false
editor: source
